Feature/hedev 617 fees numeraire
xave-finance/amm-contracts pull request #19
Opened 2022-06-27 04:26 UTC by 0xAplki

## Description of Changes
Conversion of input units to numeraire as discussed in previous discussions

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDEV-617)

## How To Test
`yarn test-local`

### Developer Checklist:

- [ ] I have followed the guidelines in our Contributing document
- [ ] This PR has a corresponding JIRA ticket
- [ ] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
- [ ] I have written new tests for your core changes, as applicable
- [ ] I have successfully ran tests locally
- [ ] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] I have successfully ran tests locally

2022-06-27 07:05 UTC, schystz reviewed
@0xAplki looks good to me, I just a couple of minor suggestions and questions

2022-06-27 07:05 UTC, schystz commented on contracts/core/CurveMath.sol
> +        // int128 _lambda = curve.lambda;
Any particular reason why remove this var and directly use `curve.lambda` on lines 123 and 124 below?

2022-06-27 08:23 UTC, 0xAplki commented on contracts/FXPool.sol
> +        (uint256 totalDepositNumeraire, ) = abi.decode(userData, (uint256, address[]));
thanks for catching!

2022-06-27 08:25 UTC, 0xAplki commented on contracts/core/CurveMath.sol
> +                _psi = calculateFee(_nGLiq, _nBals, curve, _weights);
to avoid stack too deep!

2022-06-27 08:25 UTC, 0xAplki commented on contracts/core/CurveMath.sol
> +                _psi = calculateFee(_nGLiq, _nBals, curve, _weights);
you can have variable assigned outside then you can assign something inside that scope

2022-06-27 08:27 UTC, 0xAplki commented on contracts/core/CurveMath.sol
> +        // int128 _lambda = curve.lambda;
i just did a direct reference to `curve.lambda` to save some variables.  it's just used once anyway at line 123

2022-06-27 08:43 UTC, schystz commented on contracts/core/CurveMath.sol
> +                _psi = calculateFee(_nGLiq, _nBals, curve, _weights);
Oh, nice trick!

2022-06-27 08:44 UTC, schystz commented on contracts/core/CurveMath.sol
> +        // int128 _lambda = curve.lambda;
Got it! Short answer: cause solidity sucks sometimes :D

2022-06-28 01:59 UTC, ctverceles requested changes
@0xAplki took a deeper look at the fee tests, i think we need to add in a non 0 test. Also put a suggestion for var naming but the fee recording logic looks good to me now thanks!

2022-06-28 01:59 UTC, ctverceles commented on contracts/core/FXSwaps.sol
> +    function _calculateFeeInNumeraire(int128 _amtWithEpsilon, int128 _amtWithoutEpsilon)
```suggestion
    function _calculateFeeInNumeraire(int128 _outputNumeraireAmt, int128 _inputNumeraireAmt)
```
@0xAplki better naming? 

`_amtWithoutEpsilon` to me doesn't really explain the nature of the variable. its true but it also does not contain lambda (its the input amount that the user gave). 

`_amtWithEpsilon` is actually not entirely accurate cause it also contains the result of the lambda calculation. and we're passing the output amount to the function param

2022-06-28 01:59 UTC, ctverceles commented on contracts/core/FXSwaps.sol
> +        return _amtWithEpsilon.sub(_amtWithoutEpsilon);
```suggestion
        return _amtWithEpsilon.sub(_inputNumeraireAmt);
```
@0xAplki rename var to `_inputNumeraireAmt`

2022-06-28 01:59 UTC, ctverceles commented on contracts/core/FXSwaps.sol
> +        // int128 _amtWithEpsilon = _amtWithoutEpsilon.us_mul(ONE + curve.epsilon);
```suggestion
```
clean comments if all good @0xAplki ?

2022-06-28 01:59 UTC, ctverceles commented on tests/local/pool.test.ts
> +  it('totalUnclaimedFeesInNumeraire must be minted during onJoin or onExit', async () => {
@0xAplki i think we also need to add a test here that expects a non 0 value after a swap happens and that LP tokens are minted after onJoin/onExit. so for example:
1. expect that `await fxPool.totalUnclaimedFeesInNumeraire()` returns an expected value (console log the value at this point before we do anything) 
2. trigger a swap
3. expect that `await fxPool.totalUnclaimedFeesInNumeraire()` returns the previous value + the new fees generated
4. trigger onJoinPool hook
5. expect the onJoinPool event emit
6. expect that `await fxPool.totalUnclaimedFeesInNumeraire()` is 0
7. expect that LP tokens were minted
8. trigger a swap
9. expect that `await fxPool.totalUnclaimedFeesInNumeraire()` returns the the new fees generated from the swap
10. trigger onExitPool hook
5. expect the onExitPool event emit
6. expect that `await fxPool.totalUnclaimedFeesInNumeraire()` is 0
11. expect that LP tokens were minted

2022-06-29 06:38 UTC, ctverceles requested changes
@0xAplki new test flow makes sense and works locally! 

few questions/suggestions below, though

2022-06-29 06:38 UTC, ctverceles commented on tests/local/pool.test.ts
>    // it('Previews swap caclculation from the onSwap hook using queryBatchSwap() ', async () => {})
@0xAplki are we still gonna impl this or should we remove?

2022-06-29 06:38 UTC, ctverceles commented on tests/local/pool.test.ts
>    // it('Previews swap caclculation when providing single sided liquidity from the onJoin and onExit hook', async () => {})
@0xAplki are we still gonna impl this or should we remove?

2022-06-29 06:38 UTC, ctverceles commented on tests/local/pool.test.ts
> +    expect(currentFeeBalanceAfterSwapBeforeDeposit).is.gt(previousFeeBalance)
@0xAplki a bit of extra work - but can we show this to Khidir and see if the fee result makes sense to him? if so maybe we can have an expected fee balance that we calculate in parallel to the swap tx. then we compare it against the `currentFeeBalanceAfterSwapBeforeDeposit` and expect that its equal?

2022-06-29 06:38 UTC, ctverceles commented on tests/local/pool.test.ts
> +    const previousFeeBalance = await fxPool.totalUnclaimedFeesInNumeraire()
```suggestion
    const previousFeeBalance = await fxPool.totalUnclaimedFeesInNumeraire()
    expect(previousFeeBalance).is.equals(0)
```
@0xAplki just to be airtight?

2022-06-29 06:38 UTC, ctverceles commented on tests/local/pool.test.ts
> +    expect(currentFeeBalanceAfterSwapBeforeWithdraw).is.gt(previousFeeBalance)
@0xAplki a bit of extra work - but can we show this to Khidir and see if the fee result makes sense to him? if so maybe we can have an expected fee balance that we calculate in parallel to the swap tx. then we compare it against the `currentFeeBalanceAfterSwapBeforeWithdraw ` and expect that its equal?

2022-06-29 06:38 UTC, ctverceles commented on tests/local/assimilators.test.ts
> +import { expect } from 'chai'
@0xAplki I guess this was just added in from the prior approved assimilator PR

2022-06-29 06:38 UTC, ctverceles commented on contracts/core/FXSwaps.sol
> +        return _outputNumeraireAmt.sub(_inputNumeraireAmt);
```suggestion
        return _inputNumeraireAmt.sub(_outputNumeraireAmt);
```
@0xAplki actually reading this again... shouldn't we do this the other way around like suggested here? cause `_inputNumeraireAmt` is the amount taken from user (before subtracting the swap fees). when we give the `_outputNumeraireAmt` back to the user it should be less cause lambda + epsilon was subtracted from the `_inputNumeraireAmt`.

2022-06-29 06:38 UTC, ctverceles commented on contracts/core/FXSwaps.sol
> +        accruedFees_ = -(_calculateFeeInNumeraire(_amt, inputNumeraireAmount));
@0xAplki can we run this by Khidir to see if he thinks this makes sense also?

2022-06-29 06:38 UTC, ctverceles commented on contracts/core/FXSwaps.sol
> +        accruedFees_ = _calculateFeeInNumeraire(_amt, inputNumeraireAmount);
@0xAplki can we run this by Khidir to see if he thinks this makes sense also? cause in `viewOriginSwap`, we're negating but here we're not. maybe khidir can just take a look at the math as well

2022-06-29 06:38 UTC, ctverceles commented on contracts/FXPool.sol
> -    function assimilator(address _derivative) public view returns (address assimilator_) {
@0xAplki no need for this anymore?

2022-06-29 08:40 UTC, 0xAplki commented on tests/local/pool.test.ts
>    // it('Previews swap caclculation from the onSwap hook using queryBatchSwap() ', async () => {})
i actually ask james about this, but I think we have another way of doing things. If we dont want to leave comments, we can just note this on the ticket.

2022-06-29 08:40 UTC, 0xAplki commented on tests/local/pool.test.ts
>    // it('Previews swap caclculation when providing single sided liquidity from the onJoin and onExit hook', async () => {})
same comment above

2022-06-29 08:41 UTC, 0xAplki commented on tests/local/pool.test.ts
> +    expect(currentFeeBalanceAfterSwapBeforeDeposit).is.gt(previousFeeBalance)
sure!

2022-06-29 08:45 UTC, 0xAplki commented on tests/local/assimilators.test.ts
> +import { expect } from 'chai'
the whole thing? yup! but i changed the inputs to numeraire inputs

2022-06-29 09:41 UTC, 0xAplki commented on contracts/core/FXSwaps.sol
> +        return _outputNumeraireAmt.sub(_inputNumeraireAmt);
afaik, fees are added on top of swap hence the current implementation

2022-06-30 01:40 UTC, ctverceles commented on contracts/core/FXSwaps.sol
>          _amt = _amt.us_mul(ONE - curve.epsilon);
```suggestion
        _amt = _amt.us_mul(ONE - curve.epsilon);
        accruedFees_ = -(_calculateFeeInNumeraire(_amt, inputNumeraireAmount));
```
@0xAplki i think we'll also need to switch these 2 lines like this cause `_calculateFeeInNumeraire` won't include the epsilon fee in the minting

2022-06-30 01:54 UTC, 0xAplki commented on contracts/FXPool.sol
> -    function assimilator(address _derivative) public view returns (address assimilator_) {
its already in the storage plus we have an assilimiator factory. i don't see it used so far also.

2022-06-30 01:55 UTC, ctverceles commented on contracts/core/FXSwaps.sol
> +        accruedFees_ = _calculateFeeInNumeraire(_amt, inputNumeraireAmount);
@0xAplki i see that

- in `viewOriginSwap()` its doing `ONE - curve.epsilon`
- and in `viewTargetSwap()` its doing `ONE + curve.epsilon`

I guess this is a note to run by Khidir when coming up w the expected values

2022-06-30 02:08 UTC, ctverceles commented on contracts/FXPool.sol
> +        uint256 feesToCollect = totalUnclaimedFeesInNumeraire;
```suggestion
        uint256 feesToCollect = totalUnclaimedFeesInNumeraire;
```
@0xAplki i just realized we don't have a var that records the % of `totalUnclaimedFeesInNumeraire` that we wanna give to the protocol. cause right now its minting LP tokens for total LP fees when we should only get a commission

2022-07-06 04:13 UTC, ctverceles requested changes
Small notes on the tests @0xAplki

2022-07-06 04:13 UTC, ctverceles commented on tests/local/pool.test.ts
>    it('originSwap: User batch swaps token A (USDC) for token B (fxPHP) calling the vault and triggering the onSwap hook', async () => {
@0xAplki i think its time to expect actual values on lines 455 to 457

2022-07-06 04:13 UTC, ctverceles commented on tests/local/pool.test.ts
>    it('originSwap: User batch swaps token A (fxPHP) for token B (USDC) calling the vault and triggering the onSwap hook', async () => {
@0xAplki i think its time to expect actual values on lines 410 to 412

2022-07-06 04:13 UTC, ctverceles commented on tests/local/pool.test.ts
>    // it('Previews swap caclculation when providing single sided liquidity from the onJoin and onExit hook', async () => {})
```suggestion
```
remove comments, note on ticket instead

2022-07-07 18:45 UTC, 0xAplki commented on contracts/FXPool.sol
> +        uint256 feesToCollect = totalUnclaimedFeesInNumeraire;
made a different implementation for dynamic protocol fee percentage setting

2022-07-08 10:38 UTC, 0xAplki commented on tests/local/pool.test.ts
>    it('originSwap: User batch swaps token A (USDC) for token B (fxPHP) calling the vault and triggering the onSwap hook', async () => {
Filed: https://halodao.atlassian.net/browse/HDEV-658

2022-07-08 10:38 UTC, 0xAplki commented on tests/local/pool.test.ts
>    it('originSwap: User batch swaps token A (fxPHP) for token B (USDC) calling the vault and triggering the onSwap hook', async () => {
filed: https://halodao.atlassian.net/browse/HDEV-658

2022-07-08 10:51 UTC, 0xAplki commented
Merging this from our conversation @ctverceles

2022-07-08 10:52 UTC, merged