Chore: add expected values, update plugins
xave-finance/amm-contracts pull request #20
Opened 2022-07-12 18:20 UTC by 0xAplki

## Description of Changes

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDEV-658)

## How To Test
`yarn clean && yarn compile-fix && yarn test-local`

### Developer Checklist:

- [ ] I have followed the guidelines in our Contributing document
- [ ] This PR has a corresponding JIRA ticket
- [ ] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
- [ ] I have written new tests for your core changes, as applicable
- [ ] I have successfully ran tests locally
- [ ] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] I have successfully ran tests locally

2022-07-18 08:30 UTC, mystbrent commented on contracts/FXPool.sol
> +        }
maybe add a revert when `collectorAddress` is null?

2022-07-18 08:35 UTC, mystbrent commented on tests/common/helpers/swap.ts
> +    .to.emit(fxPool, 'FeesAccrued')
maybe its good to add withArgs assertion on the `FeesAccrued` event if that's possible?

2022-07-18 08:37 UTC, mystbrent approved these changes
Overall, everything looks good awesome job @0xAplki !

Just had very minor comments was just very nitpicking

2022-07-20 09:22 UTC, 0xAplki commented on tests/common/helpers/swap.ts
> +    .to.emit(fxPool, 'FeesAccrued')
will add this on a separate task, we still have yet to make a dynamic calculation of `FeesAccrued` will file this as a ticket!

2022-07-20 09:23 UTC, 0xAplki commented on contracts/FXPool.sol
> +        }
resolving this if not additional comments

2022-07-20 11:16 UTC, ctverceles requested changes
Looks good @0xAplki ! some comments to address then we can merge i think

2022-07-20 11:16 UTC, ctverceles commented on contracts/FXPool.sol
> +        uint256,
@0xAplki is this on purpose?

2022-07-20 11:16 UTC, ctverceles commented on contracts/FXPool.sol
> +        uint256[] memory, // @todo for vault transfers
@0xAplki this still says todo, is it something we want? for internal transfers i assume?

2022-07-20 11:16 UTC, ctverceles commented on contracts/FXPool.sol
> +        uint256[] memory, // @todo for vault transfers
same here

2022-07-20 11:16 UTC, ctverceles commented on contracts/assimilators/BaseToUsdAssimilator.sol
> +    // subtracts outputAmount to baseTokenBal to simulate LP deposit
```suggestion
    // subtracts outputAmount to baseTokenBal to simulate LP withdrawal
```
oops my mistake @0xAplki

2022-07-20 11:16 UTC, ctverceles commented on scripts/pool-actions/addLiquidity.ts
> +  // console.log('liquidityToAdd:', liquidityToAdd.toString())
```suggestion
```
@0xAplki clean comments?

2022-07-20 11:16 UTC, ctverceles commented on scripts/pool-actions/index.ts
> +    // .addParam('quoteamount', 'Amount to add on quote token side')
```suggestion
```
@0xAplki clean comments?

2022-07-20 11:29 UTC, 0xAplki commented on contracts/FXPool.sol
> +        uint256,
we dont use it for now. so i just commented it out

2022-07-20 11:30 UTC, 0xAplki commented on scripts/pool-actions/addLiquidity.ts
> +  // console.log('liquidityToAdd:', liquidityToAdd.toString())
do we still need this @schystz

2022-07-20 11:31 UTC, 0xAplki commented on contracts/FXPool.sol
> +        uint256[] memory, // @todo for vault transfers
yup. commented out because its causing compiler warnings. we can just add a ticket here

2022-07-20 11:35 UTC, schystz commented on scripts/pool-actions/addLiquidity.ts
> +  // console.log('liquidityToAdd:', liquidityToAdd.toString())
It looks like not anymore since we replace `liquidityToAdd` with `numeraireAmount` @0xAplki

2022-07-20 11:59 UTC, 0xAplki commented on scripts/pool-actions/addLiquidity.ts
> +  // console.log('liquidityToAdd:', liquidityToAdd.toString())
got it

2022-07-22 06:55 UTC, ctverceles approved these changes
@0xAplki looks good to me

2022-07-22 07:01 UTC, mystbrent commented on tests/constants/mockTokenList.ts
> +    mockOraclePrice: '100007102',
q - is the price not constantly moving?

2022-07-22 07:05 UTC, mystbrent commented on tests/local/pool-simulation.test.ts
> +  const TEST_DEPOSIT_FEES = '9932' // random
might be good to have fixtures as well for these?

2022-07-22 07:10 UTC, schystz approved these changes
Approving with 1 tiny comment

2022-07-22 07:10 UTC, schystz commented on .github/workflows/node.js.yml
Just nitpicking here: can we name this action "Test" instead of "Build" on line 1 above, and line 14 "test:" instead of "build"?

This should replace "build" with "test" on github:
<img width="293" alt="Screen Shot 2022-07-22 at 3 04 09 PM" src="https://user-images.githubusercontent.com/1032707/180383133-4bcbb2f1-652a-466b-8267-5a46d01bbd3b.png">

2022-07-22 07:51 UTC, 0xAplki commented on tests/local/pool.test.ts
> +  const TEST_DEPOSIT_FAIL = '88888' // random
we can do that! but the idea here is to isolate each variables locally in the script. If we make a fixtures file we can do that when we share those constants. its easy also to edit here will doing ttd especially when we dont need those values in other scripts

2022-07-22 07:51 UTC, 0xAplki commented on tests/local/pool-simulation.test.ts
> +  const TEST_DEPOSIT_FEES = '9932' // random
same comment above!

2022-07-22 07:52 UTC, 0xAplki commented on .github/workflows/node.js.yml
can change this! thanks for catching

2022-07-22 08:02 UTC, schystz commented on .github/workflows/node.js.yml
You missed the `name: Build` on line 1 @0xAplki

2022-07-22 08:55 UTC, merged